### ISSUE TITLE
Timestamp & camera settings

### ISSUE THREAD

**Issue by atz-spe** [lbr38/motion-UI#48]
Hello,

Dans la documentation (https://motion-project.github.io/motion_config.html#text_left), je vois qu'il est indiqué que la date est affichée par défaut sur la preview de la caméra.  
Par ailleurs, je vois qu'il est possible de modifier les textes depuis les settings de la caméra dans l'UI.  

Malheureusement, aucun texte n'apparait sur la caméra, avec ou sans modification des paramètres.
Par ailleurs, les settings de la caméra ne semblent pas être pris en compte (rotate à 180 par exemple, ou user/passwd sur un flux protégé qui ne parvient pas à afficher le stream).

Des idées ?

_ps : gg pour le projet, c'est du joli taf et bien utile ! ;)_

**Comment by lbr38** [comment]
Bonjour

Merci pour le retour c'est très encourageant !
J'essaie de regarder ça rapidement.

Mais concernant les settings `rotate` et `text-left` cela m'étonne car ça devrait fonctionner. J'ai personnellement un `rotate 180` actif sur l'une de mes caméras et ça fonctionne (autant le stream que les captures motion). Je ferai un test pour vérifier le paramètre `text-left`.
Je précise juste qu'il faut forcer le redémarrage de motion si celui-ci est actif (bouton stop/start) pour prendre en compte de nouveaux paramètres car le fait de cliquer sur `Save` ne le fait pas.

Concernant l'authentification **user/passwd** il me semble que je n'avais jamais réellement réussi à la faire fonctionner. Puis c'est tombé dans l'oubli. C'est l'occasion de me repencher dessus.

N'hésitez pas à faire d'autres retours ou à soumettre des idées. C'est un projet qui n'évolue plus beaucoup car j'ai l'impression que globalement tout fonctionne pour moi et je n'ai pas eu de retours utilisateurs juste là. C'est l'occasion pour moi d'être rechallengé et de corriger des problèmes que je n'aurais pas vu ;)

**Comment by lbr38** [comment]
Bonjour

J'ai corrigé le problème d'authentification, merci de mettre à jour vers la dernière version et de prendre note de cet avertissement issu de la documentation : 

- If you specify authentication credentials for a camera, be aware that they will be stored in clear text in the motion-UI database and will be used to authenticate using the HTTP Authorization (Basic) header.

Concernant les paramètres `rotate` et `text-left`, ils sont fonctionnels, pas de correction apportée là dessus.

**Comment by atz-spe** [comment]
Merci d'avoir pris en compte ces retours aussi rapidement !  

Petite rectification concernant le text-right ; j'observe bien le timestamp de la vidéo en bas à droite, mais uniquement sur les captures enregistrées (pas sur le flux en live). Le texte est très petit d'ailleurs, je serai intéressé de savoir les paramètres à modifier pour le rendre plus grand ! Et idéalement, l'avoir aussi sur le flux en direct ;)

Autres questions, est-ce qu'il existe un moyen de définir un délai de cooldown pour la détection de mouvement ? Car j'ai l'impression que dès que le plan redevient fixe pendant une ou deux secondes, l'enregistrement s'arrête ; du coup, sur un plan de 40 secondes avec un animal qui bouge devant la caméra, cela donnera 4 ou 5 vidéos séparées dans l'UI.  
Je me disais qu'avoir une approche "j'enregistre pendant encore 10 secondes puis je stop" pourrait permettre de ne pas avoir ce soucis.
<img width="660" alt="Capture d’écran 2024-01-06 à 15 14 28" src="https://github.com/lbr38/motion-UI/assets/44492274/c4f58bca-0598-433e-abbc-eb897c59f7cf">
(exemple ici où 6 vidéos ont été prises en 2 minutes)

Dernier détail sur l'usage, quand je définie des plages horaire (autostart), par exemple 10h - 14h chaque jour, si j'appuie exceptionnellement sur le bouton pour stopper la capture à 11h30 le mardi pour arrêter de filmer quelques minutes, cela n'est pas pris en compte.

**Comment by lbr38** [comment]
> Petite rectification concernant le text-right ; j'observe bien le timestamp de la vidéo en bas à droite, mais uniquement sur les captures enregistrées (pas sur le flux en live). Le texte est très petit d'ailleurs, je serai intéressé de savoir les paramètres à modifier pour le rendre plus grand ! Et idéalement, l'avoir aussi sur le flux en direct ;)

D'accord je comprends mieux la demande.

En fait il faut bien distinguer la partie générale ``Global settings`` de la partie dédiée à motion ``Motion detection settings``.

![image](https://github.com/lbr38/motion-UI/assets/54670129/6aac3715-bf5a-40b9-beb3-0205b3bbe625)


Tout ce qui est paramétré dans ``Global settings`` s'applique au **flux en direct** ET à **motion**. En gros ce sont les paramètres de base pour que chacun des 2 fonctionnent.

Du coup dans cette logique, si vous modifiez le paramètre ``text_right`` dans ``Motion detection settings``, celui-ci s'appliquera uniquement à **motion**.

La partie flux en direct, elle, ne possède pas vraiment de paramètrage possible (hormis les paramètres de base dans ``Global settings`` qu'elle hérite) car j'estimais qu'il n'y en avait pas vraiment besoin et qu'il fallait que ça reste relativement simple.

Je n'ai jamais songé à la possibilité de pouvoir rajouter du texte à gauche ou à droite du flux en direct car il y a déjà le nom de la caméra affiché sous l'image. Maintenant si c'est un besoin réel, ça peut se développer sans trop de difficultés ;)



> Autres questions, est-ce qu'il existe un moyen de définir un délai de cooldown pour la détection de mouvement ? Car j'ai l'impression que dès que le plan redevient fixe pendant une ou deux secondes, l'enregistrement s'arrête ; du coup, sur un plan de 40 secondes avec un animal qui bouge devant la caméra, cela donnera 4 ou 5 vidéos séparées dans l'UI.
Je me disais qu'avoir une approche "j'enregistre pendant encore 10 secondes puis je stop" pourrait permettre de ne pas avoir ce soucis.

Oui je pense qu'il y a moyen d'améliorer le comportement en jouant avec les paramètres motion tels que 
- ``movie_max_time``
- ``post_capture``
- ``event_gap``
- et peut être d'autres ?

Voir https://motion-project.github.io/motion_config.html#Configuration_OptionsAlpha

En fait la configuration qui est déployée lors de l'ajout d'une caméra est essentiellement issue de mes besoins personnels. Je voulais avant tout limiter la taille des vidéos générées par motion afin qu'elles puissent être envoyées en PJ par alerte mail, d'où le fait que plusieurs "petits" fichiers soient générés.
Libre à vous de modifier ces paramètres et les adapter à vos besoins ;) J'essaierai de faire quelques tests de mon côté aussi.



> Dernier détail sur l'usage, quand je définie des plages horaire (autostart), par exemple 10h - 14h chaque jour, si j'appuie exceptionnellement sur le bouton pour stopper la capture à 11h30 le mardi pour arrêter de filmer quelques minutes, cela n'est pas pris en compte.


Oui il s'agit là du comportement normal de l'autostart qui considère que **motion** doit être démarré dans la plage horaire indiquée, quoi qu'il arrive.

Lorsque vous cliquez sur le bouton ``stop``, il est bien prit en compte mais **motion** est automatiquement redémarré par l'autostart sans que vous ne puissiez vous en rendre compte.

Pour ce cas d'usage le mieux est de d'abord désactiver l'autostart (gros bouton autostart) puis de cliquer sur le bouton ``stop``, c'est ce que je fais personnellement lorsque j'ai besoin de désactiver motion temporairement.



> Merci d'avoir pris en compte ces retours aussi rapidement !

Du coup je réouvre cette issue car je me rends compte que j'ai oublié de rendre compatible l'authentification HTTP avec les paramètres motion. Du coup ça fonctionne pour le flux en direct mais pas pour la détection de mouvement...

**Comment by lbr38** [comment]
Bonjour

Dans la dernière release, j'ai ajouté la possibilité d'afficher du texte à gauche ou à droite sur le stream, reste à voir si la taille est suffisante ;) J'ajouterai plus tard la possibilité d'afficher la date et l'heure.

L'authentification HTTP fonctionne.

**Comment by lbr38** [comment]
Mince ce n'est pas normal qu'il redémarre en boucle. Et en effet l'erreur indique qu'il manque une colonne en base de données. Cette nouvelle colonne est censée être créée automatiquement lors de la mise à jour `4.0.0`. 

J'ai toujours mis à jour en suivant les étapes du wiki et jamais via docker-compose.
Essayez d'utiliser `flush` et dites moi si ça arrange le problème, sinon je vous donnerai des commandes pour créer la colonne manquante.

Dans la mesure du possible, utiliser la méthode de mise à jour du wiki car c'est la seule que je teste et que je peux garantir :)

**Comment by atz-spe** [comment]
Re-fonctionne après rm du volume :)  
Je verrais si j'arrive à reproduire cela pour trouver une solution faisant persister les données de la db.

**Comment by lbr38** [comment]
Si ça peut aider, voici le fichier docker-compose que j'utilise pour builder automatiquement une nouvelle image à chaque sortie de mise à jour : 

https://github.com/lbr38/motion-UI/blob/main/docker/docker-compose.yml

**Comment by lbr38** [comment]
Bonjour

La dernière release intègre la possibilité d'afficher la date et l'heure sur le stream. Je vous laisse voir si cela convient, peut être que j'intègrerai à l'avenir la possibilité de changer la couleur du texte au cas où le blanc soit problématique sur certaines images.

Concernant la taille du texte sur les captures motion, j'ai trouvé que c'est le paramètre `text_scale` qui permet de la modifier.
