### ISSUE TITLE
Motion event always after motion started

### ISSUE THREAD

**Issue by LeTak0** [lbr38/motion-UI#62]
When the Motion service start (manual or time based) it always creates an event for motion and makes a video.

Would it be possible to fix it by adding a cooldown/timeout after the motion service started?

**Comment by lbr38** [comment]
I sometimes also experience this behavior too. There's nothing I can do at my level, it depends on the motion program itself.

I found an issue with a similar problem: https://github.com/Motion-Project/motion/issues/541

May be you could ask Motion's developer to add an option to delay the start of detection at the start of motion?
